version: 2

sources: 
  - name: jaffle_shop 
    database: raw 
    schema: jaffle_shop 
    tables:
      - name: customers
        description: One record per customer 
      - name: orders 
        description: One record per order. Includes cancelled and deleted orders as well.